import LocalizedStrings from 'react-native-localization';
const Strings = new LocalizedStrings({
  en: {
    CompanyName:'FSP Media for Bussiness',
    PleaseEnterNote: 'Note can not be empty.',
    DeliveryAddress:'Delivery Address',
    PleaseSelectAddress:'Add your delivery address to get started.',
    FetchingMenu: 'Fetching Menu..',
    DeniedCameraAccess: 'You have Denied Camera access, Please give access to get a discount.',
    GoTOSettings: 'Go to Settings',
    DriverDepartureTime: 'Driver Departure Time',
    DriverNotAvailable: 'Waiting for driver assignement from ordaraty',
    Driver: 'Driver',
    ItemTotal: 'Item Total',
    EnterSpecialNote: 'Enter Special Note',
    SpecialNote: 'Special Note (optional)  Max. 40 char',
    Done: 'Done',
    Note: 'Special Note',
    Address: 'Address',
    Navigate: 'Navigate',
    MarkAsComplete: 'Mark As Completed',
    CustomerName: 'Customer',
    Addresses: 'My Addesses',
    YourOrderWillbeDeliveredSoon: 'Your Order will be delivered soon',
    CongratulationYourOrderHasBeenBooked: 'Congratulation Your Order has been Booked',
    MyCart: 'My Cart',
    NoModifersAvailable: 'No Modifers available',
    Addon: 'Addon',
    FinalTotal: 'Final Total',
    TaxPlus: '+ Tax',
    DeliveryCharge: '+ Delivery Charge',
    Discount: '- Discount',
    SubTotal: 'Sub Total',
    Checkout: 'Checkout',
    OtherSettings: 'Other Settings',
    NewToFSP: 'New to FSP ?',
    Proceed: 'Proceed',
    DeliveryTxt: 'I want delivery',
    Takeaway: 'Takeaway',
    Favourites: 'Favourites',
    NoFranchiseFound: 'No franchise found for your search.',
    AppName: 'Magnet',
    SmileorLaugh: 'Smile as much as you can to earn surprising discount.',
    smileMsg: 'Capture your smiling face and send to Ordaraty App. Ordaraty will find your smile and provide discount on this order.',
    TakePicture: 'Capture Face',
    DiscountMsg1: 'You’ve got ',
    DiscountMsg2: ' discount on this order.',
    GotIt: 'Got It',
    Congrats: 'Congrats!',
    noDiscount: 'Try your luck in next order.',
    Okay: 'Okay',
    Opps: 'We could not detect your smile as much we expect. Better luck in next order!',
    Name: 'Your Name',
    BranchIdPlaceHolder: 'Enter Branch Id',
    Offers: 'Offers',
    TravelFilterType: 'Travel Type',
    TravelFilterCategory: 'Categories',
    DateFilterRange: 'Date Range',
    PriceIn: 'Price in',
    PriceRange: 'Price Range',
    Tags: 'Tags',
    LocationError: 'Location is not available..',
    English: 'English',
    Arabic: 'Arabic',
    NameStar: 'Name*',
    Phone: 'Phone',

    PhoneNumberStar: 'Phone Number*',
    PhoneStar: 'Phone *',
    Destination: 'Destination',
    AlreadyHaveAccount: 'Already have an account?',
    EmailStar: 'Email address *',
    EmailAddress: 'Email address',
    Password: 'Password*',
    RemoveAll: 'Clear All',
    PasswordStar: 'Password*',
    CreateNewAccountQuestion: 'Create account?',
    SignIn: 'Sign In',
    Clear: 'CLEAR',
    SignUp: 'SIGN UP',
    DriverLogin: 'Driver Login',
    SignUpGoogle: 'Or Sign up with',
    SignInGoogle: 'Or Login with',
    TourismAgencies: 'Travel Agencies',
    SelectYourTravelAgent: 'Select Your Travel Agent',
    AreYouCompany: 'Are you a company? join us',
    Skip: 'Skip',
    AddressLine1: 'Address Line 1',
    AddressLine2: 'Address Line 2',
    City: 'City',
    Country: 'Country',
    ForgotPassword: 'forgot login Details? ',
    getHelp:'Get Help',
    PleaseEnterName: 'Please enter name',
    PleaseEnterEmail: 'Please enter email',
    PleaseEnterPassword: 'Please enter password',
    PleaseEnterPhone: 'Please enter Phone',
    PleaseEnterPhoneNumber: 'Please enter phone number',
    PleaseEnterValidEmail: 'Please enter a valid email',
    PleaseEnterOtp: 'Please enter OTP',
    PleaseEnterBranchId: 'Please enter branch id',
    PleaseEnterAccessCode: 'Please enter access code',
    OtpResendSuccessfully: 'Otp Resent Successfully',
    MyProfile: 'My Profile',
    EditProfile: 'Edit Profile',
    MyWishlist: 'Wishlist',
    Stores: 'Custom Plan',
    AddressBook: 'Address Book',
    OrderHistory: 'Order History',
    PushNotification: 'Push Notification',
    Logout: 'Logout',
    Login: 'LOGIN',
    PhoneColon: 'Phone: ',
    Delete: 'Delete',
    AddToWishlist: 'Add To Wishlist',
    MoveToBag: 'Move to Bag',
    Total: 'Total',
    Length: 'Length',
    Height: 'Height',
    Width: 'Width',
    Weight: 'Weight',
    Description: 'Description',
    TryThisOn: 'Try this on',
    MyLook: 'My Look',
    InternetNotConnected:
      'Please check your Internet connection.',
    Apply: 'Apply',
    Edit: 'Edit',
    Save: 'Save',
    Remove: 'Remove',
    AreYouSureYouWantToRemoveItem:
      'Are you sure you want to remove this address?',
    AreYouSureYouWantToRemoveCartItem:
      'Are you sure you want to remove this cart item?',
    AreYouSureWantToClearCart: 'Are you sure you want to clear cart?',
    Yes: 'Yes',
    No: 'No',
    NoDataAvailable: 'No Data Available',
    NoFranchiseAvailable: 'No Franchise Available',
    NoFavouritesAvailable: 'No Favourites Available',
    NoItemsAvailable: 'No Items Available',
    ItemAddedToWishlist: 'Item added to Wishlist',
    RecentlyView: 'Recently View',
    ViewAll: 'View All',
    Next: 'Next',
    NoProductsAvailable: 'No products available',
    EndNoMoreProducts: 'End - no more products',
    NoStoresAvailable: 'No package available',
    FullName: 'Full Name',
    PleaseEnterAllFields: 'Please enter all fields',
    PleaseEnterFullName: 'Please enter Full Name',
    ZipPinCode: 'Zip/Pin code',
    PleaseEnterAddressline1: 'Please enter Address Line1',
    PleaseEnterAddressline2: 'Please enter Address Line2',
    PleaseEnterCity: 'Please enter City',
    PleaseEnterCountry: 'Please enter Country',
    PleaseEnterZipPinCode: 'Please enter Zip/Pin code',
    Update: 'Update',
    MakeDefault: 'Make default',
    SizeColon: 'Size: ',
    TaxColon: 'Tax: ',
    TotalColon: 'Total: ',
    TermsAndConditions: 'Terms & Conditions',
    PrivacyPolicy: 'Privacy Policy',
    ReturnPolicy: 'Return Policy',
    Settings: 'Settings',
    RateThisApp: 'Rate App',
    Filter: 'FILTER',
    Sort: 'Sort',
    ResetFilters: 'Reset Filters',
    AreYouSureYouWantToResetYouFilters:
      'Are you sure you want to reset your filters?',
    Reset: 'Reset',
    NameMustBeGreaterThanTwo: 'Name must be greather than 2 characters.',
    PleaseEnterZipcode: 'Please enter zipcode',
    AreYouSureYouWantToLogout: 'Are you sure you want to Logout?',
    ChangeAddress: 'Change Address',
    NoMoreProduct: 'No More Product.',
    PremiumStores: 'Request Custom Plan',
    MyAccount: 'My Account',
    Others: 'Others',
    SectionLogout: 'Logout',
    ReportAProblem: 'Report a problem',
    PersonalDetail: 'Personal Detail',
    OrderHistory: 'Order History',
    Wishlist: 'Wishlist',
    Cart: 'Cart',
    RecentSearch: 'Recent Search',
    Login: 'LOGIN',
    WISHLIST: 'Wishlist',
    SHARE: 'Share',
    LOCATION: 'Map',
    LOCATION2: 'Location',
    LIKES: 'Likes',
    CURRENCY_BD: 'BD',
    CURRENCY_SAR: 'SAR',
    OVERVIEW: 'OVERVIEW',
    INTINERARY: 'INTINERARY',
    Offered_By: 'Offered By',
    Interested: 'Interested?',
    Contact_now: 'Contact Now',
    Likes: 'Likes',
    Cities: 'Cities',
    Hotels: 'Hotels',
    Countries: 'Countries',
    Dates: 'Dates',
    Days: 'No. of days',
    Day: 'Days',
    Night: 'Nights',
    Adult: 'Adult',
    Infant: 'Infant',
    Kids: 'Kids',
    ProfileSetting: 'Profile Setting',
    Username: 'Username',
    Country: 'Country',
    Gender: 'Gender',
    CustomPlan: 'Custom Plan',
    Duration: 'Duration',
    NoOfTravellers: 'No. Of Travellers',
    FromDate: 'From : Date',
    From: 'From',
    To: 'TO',
    ToDate: 'To : Date',
    InfantUnder: 'under 2Y',
    InfantUnder12: 'Under 12Y',
    Submit: 'Submit',
    EnterAddDetails: 'Enter Additional Information here',
    loginError: 'Please login',
    CustomPlanSuccessMessage:
      'Your Custom Plan has been successfully saved..!!',
    SomethingWentWronge: 'Something Went Wronge..!!',
    FromIsEmpty: 'Please mention the from and to destinations',
    ToIsEmpty: 'Please mention the from and to destinations',
    // fromIsEmpty:'From field can not be empty'
    Thankyou: 'Thank You',
    Error: 'Error',
    Call: 'Call',
    OptionText: 'Select an option',
    Camera: 'Camera',
    Gellery: 'Gallery',
    Cancel: 'Cancel',
    ImageWarning: 'Please select Jpeg image',
    ViewTrip: 'VIEW TRIP',
    ViewOffer: 'VIEW OFFER',
    TopTrip: 'Top Trips',
    UserUpdateProfile: 'Your profile is updated successfully',

    // change password
    ChangePassword: 'Change Password',
    CurrentPassword: 'Current Password',
    NewPassword: 'New Password',
    ConfirmNewPassword: 'Confirm New Password',
    PasswordDoNotMatch: 'New Password and Confirm Password do not match',
    ConfirmPasswordEmpty: 'Please provide the confirm password',
    NewPasswordEmpty: 'Please mention the New password fields',
    OldPasswordEmpty: 'Please mention the Old password fields',
    SuccessMessage: `Password is changed, Please login again.`,

    //new strings
    Title: 'Title',
    Message: 'Messages',
    ShareApp: 'Share App',
    ContactUs: 'Contact Us',
    Support: 'Support & FAQ',
    FAQs: 'FAQs',
    EmailUserName: 'Email/Username',
    ForgotPassword2: 'forgot login Details? ',
    getHelp:'Get Help',
    NotAMemberYet: 'Not a member yet?',
    AlreadyaMember: 'already member?',
    Report: 'Report',
    Option1: 'Price Low to High',
    Option2: 'Price High to Low',
    Option3: 'Sort by Date',
    Option4: 'Sort by title A-Z',
    NoFacilities: 'No Facilities',
    Notifications: 'Notification',

    SortingOptions: 'Select Sorting Option',
    CurrencyTitle: 'Please Select Your Currency..!!',
    LanguageTitle: 'Please Select Your Language..!!',
    ChangeCurrency: 'Change Currency',
    Status: 'Status',
    AlreadyMember: 'Already a member? Login',
    NotAMember: 'Not a member yet? Sign Up',
    ChangeLanguage: 'Change Language',
    AdultError: 'Please provide number of adults and kids',
    TravelFilterType: 'Travel Type',
    TravelFilterCategory: 'Travel Category',
    DateFilterRange: 'Date Range',
    Tags: 'Tags',
    PriceIn: 'Price in',
    PriceRange: 'Price Range',
    PriceDetails: 'Price Details',
    Country: 'Country',
    Explore: 'EXPLORE',
    CallValidation_Dialog: 'Attention!',

    // Comman strings
    Order: 'Order',
    OrderNo: 'Order No: # ',
    Items: 'Items to Deliver',
    CustomerItems: 'Items',
    PhoneNumber: 'Phone Number',
    PhoneNumber: 'Mobile Number',
    AccessCode: 'Enter AccessCode',
    GetOTP: 'Next',
    OTP:'Verify OTP',
    Verify:'VERIFY',
    SignUpWithFacebook: 'SignUp With Facebook',
    ContinueWithFacebook: 'Continue With Facebook',
    EnterOTP: 'You will receive verification code in few seconds',
    ResendOTP: 'Resend Code',
    Add: 'Add',
    BD: 'BD',
    Search: 'Search',
    AddToCart: 'Add To Cart',
    SearchResult: 'Search Results',
    Email: 'Email',
    PhoneNo: 'Phone No.',
    ChangePhone: 'Change Phone',
    Close: 'CLOSE',
    City: 'City *',
    Block: 'Block No. *',
    House: 'House/Apt# *',
    Road: 'Road *',
    AddressAddedMsg: 'Address Added',
    AddressUpdatedMsg: 'Address Updated',
    AddressNotEmptyMsg: 'Address fields should not be Empty.',
    ManageAddresses: 'Manage Addresses',
    Addnewaddress: '+ Add new address',
    PleaseSetYourDefaultAddress: 'Please Set Your Default Address First',

    //Ordaraty Specific

    ItemAdded: 'Item added to your cart.',
    WelcomeLogin: 'Welcome',
    SMILE: 'SMILE & GET DISCOUNT',
    Welcome: 'Code Sent!',
    LoginWithPhoneOrFacebook: 'Enter username and password to login',
    SignUpWithPhoneOrFacebook: 'Register your number & receive daily food deals.',
    UseCurrentLocation: 'Use Current Location',
    UsingYourPhoneGPS: 'Using your phone GPS',
    OR: 'OR',
    DragMap: 'Drag map to locate your address',
    SavedAddress: 'Saved Addresses',
    New: 'New',
    Delivery: 'DELIVERY',
    TakeAway: 'TAKEAWAY',
    Franchise: 'Franchise',
    Filters: 'Filters',
    RecentOrders: 'Recent Orders',
    MostPopularItems: 'Most Popular Items',
    MostLatestItems: 'New Items',
    MostPopularBranches: 'Most Popular Branches',
    SeeMore: 'See More',
    SearchBarPlaceHolder: 'Search for franchise',
    Branches: 'Branches',
    Modifiers: 'Modifiers',
    Toppings: 'Toppings',
    Customizeifyouwant: 'Customize if you want',
    EnterNewPhone: 'Enter new Phone No.',
    AddNewAddress: 'Add New Address',
    SelectAddress:'Select Address',
    WelcomeGuest: 'Welcome Guest',
    ModifiersNotAvailable: 'Modifiers Not Available',
    CartIsEmpty: 'Cart is empty, Please add Item first.',
    Customize: 'CUSTOMIZE',
    GoBack: 'Go back',
    Default:'Default'

  },
  ar: {
    CompanyName:'FSP Media for Bussiness',
    PleaseEnterNote: 'Note can not be empty.',
    DeliveryAddress:'Delivery Address',
    PleaseSelectAddress:'Add your delivery address to get started.',
    FetchingMenu: 'Fetching Menu..',
    DeniedCameraAccess: 'You have Denied Camera access, Please give access to get a discount.',
    GoTOSettings: 'Go to Settings',
    DriverDepartureTime: 'Driver Departure Time',
    DriverNotAvailable: 'Waiting for driver assignement from ordaraty',
    Driver: 'Driver',
    PleaseSetYourDefaultAddress: 'Please Set Your Default Address First',
    ItemTotal: 'Item Total',
    EnterSpecialNote: 'Enter Special Note',
    SpecialNote: 'Special Note (optional) Max. 40 char',
    Done: 'Done',
    Note: 'Special Note',
    Address: 'Address',
    Navigate: 'Navigate',
    MarkAsComplete: 'Mark As Completed',
    CustomerName: 'Customer',
    YourOrderWillbeDeliveredSoon: 'Your Order will be delivered soon',
    CongratulationYourOrderHasBeenBooked: 'Congratulation Your Order has been Booked',
    Addresses: 'My Addesses',
    MyCart: 'My Cart',
    NoModifersAvailable: 'No Modifers available',
    Addon: 'Addon',
    FinalTotal: 'Final Total',
    TaxPlus: '+ Tax',
    DeliveryCharge: '+ Delivery Charge',
    Discount: '- Discount',
    SubTotal: 'Sub Total',
    Checkout: 'Checkout',
    OtherSettings: 'Other Settings',
    NewToFSP: 'New to FSP  ?',
    Proceed: 'Proceed',
    DeliveryTxt: 'I want delivery',
    Takeaway: 'Takeaway',
    Favourites: 'Favourites',
    NoFranchiseFound: 'No franchise found for your search.',
    AppName: 'Ordaraty',
    SmileorLaugh: 'Smile as much as you can to earn surprising discount.',
    smileMsg: 'Capture your smiling face and send to Ordaraty App. Ordaraty will find your smile and provide discount on this order.',
    TakePicture: 'Capture Face',
    DiscountMsg1: 'You’ve got ',
    DiscountMsg2: ' discount on this order.',
    GotIt: 'Got It',
    Congrats: 'Congrats!',
    noDiscount: 'Try your luck in next order.',
    Okay: 'Okay',
    Opps: 'We could not detect your smile as much we expect. Better luck in next order!',
    Status: 'الحالة',
    Name: 'الأسم',
    NameStar: 'الإسم*',
    Phone: 'رقم الهاتف',
    PhoneNumberStar: 'رقم الهاتف*',
    PhoneStar: 'Phone*',
    AlreadyHaveAccount: 'هل لديك حساب ؟?',
    EmailStar: 'البريد الألكتروني*',
    EmailAddress: 'البريد الإلكتروني',
    Password: 'كلمة المرور',
    PasswordStar: 'كلمة المرور*',
    CreateNewAccountQuestion: 'سجل حساب جديد‫!‬?',
    SignIn: 'تسجيل دخول',
    Clear: 'مسح البيانات',
    SignUp: 'تسجيل جديد',
    DriverLogin: 'Driver Login',
    SignUpGoogle: 'أو سجل حساب جديد',
    SignInGoogle: 'سحل دخول بحساب قوقل',
    Skip: 'تخطي',
    AddressLine1: 'العنوان',
    AddressLine2: 'تفاصيل العنوان ',
    City: 'المدن',
    Country: 'الدولة',
    ForgotPassword: 'هل نسيت كلمة السر ؟',
    PleaseEnterName: 'أدخل اسم الدخول',
    PleaseEnterEmail: 'ادخل البريد الألكتروني',
    PleaseEnterPassword: 'أدخل كلمة السر',
    PleaseEnterPhone: 'أدخل رقم الهاتف',
    PleaseEnterPhoneNumber: 'الرجاء إدخال رقم الهاتف',
    PleaseEnterValidEmail: 'الرجاء كتابة البريد الإلكتروني بصوره صحيحه',
    MyProfile: 'حسابي',
    EditProfile: 'تعديل الملف الشخصي',
    MyWishlist: ' الامنيات',
    Stores: 'رحلة مخصصه',
    AddressBook: 'جهات الإتصال',
    OrderHistory: 'Order History',
    PushNotification: 'الإشعارات',
    Logout: 'تسجيل خروج',
    Login: 'تسجيل دخول',
    PhoneColon: 'رقم الهاتف: ',
    Delete: 'حذف',
    AddToWishlist: 'إضافة إلى قائمة الامنيات',
    MoveToBag: 'إضافة إلى سلة المشتريات',
    Total: 'الجموع',
    Length: 'الطول',
    Height: 'الارتفاع',
    Width: 'العرض',
    Weight: 'العرض',
    Description: 'الوصف',
    TryThisOn: 'جرب هذا‫..‬',
    MyLook: 'مشاهداتي',
    InternetNotConnected: 'Please check your Internet connection.',
    Apply: 'تحديث',
    Edit: 'تعديل',
    Save: 'حفظ',
    Remove: 'حذف',
    Yes: 'موافق',
    No: 'لا',
    NoDataAvailable: 'لا يوجد بيانات',
    NoFranchiseAvailable: 'No Franchise Available',
    NoFavouritesAvailable: 'No Favourites Available',
    NoItemsAvailable: 'No Items Available',
    ItemAddedToWishlist: 'تم اضافة الخدمة إلى قائمة الامنيات',
    RecentlyView: 'شاهدت مؤخراً',
    ViewAll: 'عرض الكل',
    Next: 'التالي',
    NoProductsAvailable: 'الخدمة غير متوفرة',
    EndNoMoreProducts: 'لا يوجد خدمات اكثر‫-‬ النهاية',
    NoStoresAvailable: 'لا يوجد رحلات اضافية',
    FullName: 'الاسم بالكامل',
    PleaseEnterFullName: 'الرجاء إدخال الإسم بالكامل',
    ZipPinCode: 'الرمز البريدي',
    PleaseEnterAddressline1: 'الرجاء إدخال العنوان ',
    PleaseEnterAddressline2: 'الرجاء إدخال العنوان ‫-‬ مزيد من العلومات',
    PleaseEnterCity: 'الرجاء إدخال المدينة',
    PleaseEnterCountry: 'الرجاء إدخال الدولة',
    PleaseEnterZipPinCode: 'الرجاء إدخال الزمز البريدي',
    Update: 'تحديث',
    MakeDefault: 'حفظ ك إفتراضي',
    SizeColon: 'الححم: ',
    TaxColon: 'القيمة المضافه: ',
    TotalColon: 'المجموع: ',
    TermsAndConditions: 'الشروط و الأحكام',
    PrivacyPolicy: 'سياسة الخصوصية',
    ReturnPolicy: 'سياسة الإسترجاع',
    Settings: 'الإعدادات',
    RateThisApp: 'قيم تطبيق تيك اوف',
    Filter: 'تصفية',
    Sort: 'فرز',
    ResetFilters: 'مسح التصفية',
    AreYouSureYouWantToResetYouFilters: 'هل انت متأكد من مسح التصفية ؟',
    Reset: 'إعادة تعيين',
    NameMustBeGreaterThanTwo: 'سجب ان يكون الأسم مكون من ثلاث حروف أو اكثر',
    PleaseEnterZipcode: 'أدخل الزمز البريدي',
    AreYouSureYouWantToLogout: 'هل تريد تسجيل الخروج؟',
    ChangeAddress: 'تغيير العنوان',
    NoMoreProduct: 'لا مزيد من المنتجات',
    PremiumStores: 'طلب رحلة خاصة',
    MyAccount: 'حسابي',
    Others: 'أخرى',
    SectionLogout: 'تسجيل خروج',
    ReportAProblem: 'الإبلاغ عن مشكلة',
    PersonalDetail: 'البيانات الشخصية',
    OrderHistory: 'سجل العمليات',
    Wishlist: 'قائمة الامنيات',
    Cart: 'سلة المشتريات',
    RecentSearch: 'البحث مؤخراً',
    Login: 'تسجيل الدخول',
    WISHLIST: 'قائمة الإمنيات',
    SHARE: 'مشاركه',
    LOCATION: 'الموقع',
    LOCATION2: 'الموقع٢',
    LIKES: 'إعجاب',
    CURRENCY_BD: 'دب',
    CURRENCY_SAR: 'رس',
    OVERVIEW: 'نظرة عامه',
    INTINERARY: 'مسار الرحلة',
    Offered_By: 'الشركة',
    Interested: 'مهتم ؟',
    Contact_now: 'الاتصال بي',
    Likes: 'إعجاب',
    Cities: 'المدن',
    Hotels: 'الفنادق',
    Countries: 'الدول',
    Dates: 'التواريخ',
    Days: 'عدد الإيام',
    Day: 'الأيام',
    Night: 'الليالي',
    Adult: 'بالغ',
    Infant: 'رضيع',
    Kids: 'طفل',
    ProfileSetting: 'إعدادت حسابي',
    Username: 'اسم الدخول',
    Country: 'الوجهة',
    Gender: 'الجنس',
    CustomPlan: 'رحلة حسب الطلب',
    Duration: 'مدة الرحلة',
    NoOfTravellers: 'عدد المسافرين',
    FromDate: 'من : التاريخ',
    From: 'من',
    To: 'إلى',
    ToDate: 'إلى',
    InfantUnder: 'أقل من سنتين',
    InfantUnder12: 'أقل من ١٢ سنه',
    Submit: 'إرسال',
    EnterAddDetails: 'ادخل مزيد من التفاصيل',
    loginError: 'الرجاء تسجيل الدخول',
    CustomPlanSuccessMessage: 'تم حفظ المعلومات',
    SomethingWentWronge: 'حدث خطأ ما‫!!‬',
    FromIsEmpty: 'الرجاء إدخال بلد المغادرة',
    ToIsEmpty: 'أدخل بلد الوجهه',
    // fromIsEmpty:'لا يمكن ترك بلد الوجهه فارغاً'
    Thankyou: 'شكراً لك',
    TourismAgencies: 'وكالات السفر',
    SelectYourTravelAgent: 'حدد وكالة السفر',
    AreYouCompany: 'هل انت شركة ؟ انضم لنا',
    Error: 'خطأ',
    Call: 'اتصال',
    OptionText: 'حدد خياراً',
    Camera: 'الكاميرا',
    Gellery: 'ألبوم الصور',
    Cancel: 'إلغاء',
    ImageWarning: 'أختر صورة JEPG',
    ViewTrip: 'عرض الرحلة',
    ViewOffer: 'View Offer',
    TopTrip: 'أفضل الرحلات',
    // change password
    ChangePassword: 'تغيير كلة السر',
    CurrentPassword: 'كلمة المرور القديمة',
    NewPassword: 'كلمة المرور الجديدة',
    ConfirmNewPassword: 'تأكيد كلمة المرور الجديد',
    PasswordDoNotMatch: 'كلمة المرور الجديدة لا تطابق',
    ConfirmPasswordEmpty: 'الرجاء ادخال تأكيد كلمة المرور الجديدة',
    NewPasswordEmpty: 'الرجاء إدخال كلمة المرور الجديدة',
    OldPasswordEmpty: 'الرجاء إدخال كلمة المرور القديمة',
    SuccessMessage: 'تم تيغر كلمة السر، الرجاء تسجيل الدخول مرة آخرى',
    AlreadyMember: 'هل انت عضو؟ سجل دخول',
    NotAMember: 'لست عضواً ؟ سجل الآن',
    ChangeLanguage: 'تغيير اللغة',
    English: 'الإنجليزية',
    Arabic: 'العربية',
    LanguageTitle: 'الرجاء اختيار اللغة',
    AdultError: 'الرجاء تحديد مسافر بالغ على الأقل',
    UserUpdateProfile: 'تم تحديث حسابك بنجاح',
    Option1: 'الجديد',

    //new strings

    Title: 'عنوان',
    Message: 'الرسائل',
    ShareApp: 'شارك التطبيق',
    ContactUs: 'اتصل بنا',
    Support: 'الدعم الفني',
    FAQs: 'FAQs',
    EmailUserName: 'الايميل/اسم الدخول',
    ForgotPassword2: 'هل نسيت كلمة السر',
    NotAMemberYet: 'لست عضواً ؟ سجل الآن',
    AlreadyaMember: 'هل انت عضو ؟',
    Report: 'ابلغ عن الرحلة',
    Option1: 'السعر الأقل سعراً أولاً',
    Option2: 'السعر الأعلى سعراً أولاً',
    Option3: 'حسب التاريخ',
    Option4: 'حسب الترتيب الابجدي',
    NoFacilities: 'No Facilities',
    Notifications: 'الإشعارات',
    SortingOptions: 'حدد خيار الفرز',
    RemoveAll: 'مسح الكل',
    ChangeCurrency: 'تغيير العملة',
    Destination: 'المكان المقصود',
    TravelFilterType: 'نوع الرحلة',
    TravelFilterCategory: 'تصنيف الرحلة',
    DateFilterRange: 'نطاق الرحلة',
    Tags: 'الكلمات المفتاحيه',
    PriceIn: 'Price in',
    PriceDetails: 'تفاصيل السعر',
    Country: 'الدولة',
    LocationError: 'الدولة غير متوفرة',
    Offers: 'العروض',
    Explore: 'أكتشف',
    CallValidation_Dialog: 'Attention!',

    // Comman strings
    Order: 'Order',
    OrderNo: 'Order',
    Items: 'Items to Deliver',
    CustomerItems: 'Items',
    PhoneNumber: 'رقم الهاتف',
    OTP:'Verify OTP',
    Verify:'VERIFY',
    GetOTP: 'Next',
    ContinueWithFacebook: 'Continue With Facebook',
    EnterOTP: 'You will receive verification code in few seconds',
    ResendOTP: 'Resend Code',
    Add: 'Add',
    BD: 'BD',
    Search: 'Search',
    AddToCart: 'Add To Cart',
    SearchResult: 'Search Results',
    Email: 'Email',
    PhoneNo: 'Phone No.',
    ChangePhone: 'Change Phone',
    Close: 'CLOSE',
    City: 'City *',
    House: 'House/Apt# *',
    Block: 'Block No. *',
    Road: 'Road *',
    AddressAddedMsg: 'Address Added',
    AddressUpdatedMsg: 'Address Updated',
    AddressNotEmptyMsg: 'Address fields should not be Empty.',
    ManageAddresses: 'Manage Addresses',
    Addnewaddress: '+ Add new address',
    SelectAddress:'Select Address',
    Delivered: 'Delivered',
    InProgress: 'In Progress',
    Cancelled: 'Cancelled',


    AreYouSureYouWantToRemoveItem:
      'Are you sure you want to remove this address?',
    //Ordaraty Specific

    ItemAdded: 'Item added to your cart.',
    WelcomeLogin: 'Welcome',
    SMILE: 'SMILE & GET DISCOUNT',
    Welcome: 'Code Sent!',
    LoginWithPhoneOrFacebook: 'Enter phone number to login',
    SignUpWithPhoneOrFacebook: 'Register your number & receive daily food deals.',
    UseCurrentLocation: 'Use Current Location',
    UsingYourPhoneGPS: 'Using your phone GPS',
    OR: 'OR',
    DragMap: 'Drag map to locate your address',
    SavedAddress: 'Saved Addresses',
    New: 'New',
    Delivery: 'DELIVERY',
    TakeAway: 'TAKEAWAY',
    Franchise: 'Franchise',
    Filters: 'Filters',
    RecentOrders: 'Recent Orders',
    MostPopularItems: 'Most Popular Items',
    MostLatestItems: 'New Items',
    MostPopularBranches: 'Most Popular Branches',
    SeeMore: 'See More',
    SearchBarPlaceHolder: 'Search for franchise',
    Branches: 'Branches',
    Modifiers: 'Modifiers',
    Toppings: 'Toppings',
    Customizeifyouwant: 'Customize if you want',
    EnterNewPhone: 'Enter new Phone No.',
    AddNewAddress: 'Add New Address',
    Delivered: 'Delivered',
    InProgress: 'In Progress',
    Cancelled: 'Cancelled',
    WelcomeGuest: 'Welcome Guest',
    ModifiersNotAvailable: 'Modifiers Not Available',
    CartIsEmpty: 'Cart is empty, Please add Item first.',
    Customize: 'CUSTOMIZE',
    GoBack: 'Go back',
    Default:'Default'
  },
});

export default Strings;
